version: '3.8'

services:
  PostgreSQL:
    image: 'postgres:14.2-alpine3.15'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db