spring.profiles.active: dev-local
spring.jmx.enabled: false

info.app.name: User Service
info.app.description: Service to register and manage users
info.app.active-profile: ${spring.profiles.active}

