logging.config: classpath:log4j2-dev.yml

#Actuator setup
#Enabling only the info endpoint
management.endpoints.enabled-by-default: false
management.endpoint.info.enabled: true
management.endpoints.web.exposure.include: info
management.endpoints.jmx.exposure.exclude: "*"

server.port: 8080

scheduler.rest.core.pool.size: 2
scheduler.rest.max.pool.size: 5
scheduler.rest.keep.alive.time.secs: 120
scheduler.rest.queue.max.size: 50

spring:
  sql.init.platform: "postgres"
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://host.docker.internal:5432/db"
    username: "user"
    password: "password"

